/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";


// =====================================================================
// 🚀 终极防崩补丁：骗过 React 19/RSC 的 devtools，修复 createTask 报错
// =====================================================================
try {
  if (typeof console !== 'undefined') {
    Object.defineProperty(console, 'createTask', {
      value: () => ({
        // 伪造一个 run 方法，拿到回调函数直接执行，假装无事发生
        run: (cb: any) => cb()
      }),
      writable: true,
      configurable: true
    });
  }
} catch (e) {
  // 忽略补丁失败的情况
}
// =====================================================================

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
  GITHUB_TOKEN?: string;
  [key: string]: unknown;
}

// 一次性注入：Cloudflare secrets 不可枚举，需显式按名字读取
let envInjected = false;

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (!envInjected) {
      if (env.GITHUB_TOKEN) process.env["GITHUB_TOKEN"] = env.GITHUB_TOKEN;
      envInjected = true;
    }

    const url = new URL(request.url);
    
    // Image optimization via Cloudflare Images binding
    if (url.pathname === "/_vinext/image") {
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      });
    }

    // Delegate everything else to vinext
    return handler.fetch(request);
  },
};
