/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
  GITHUB_TOKEN?: string;
  [key: string]: unknown;
}

// Cloudflare Worker secrets 是不可枚举的，必须显式按名字读取
const SECRET_KEYS = ["GITHUB_TOKEN"] as const;

function injectEnvToProcess(env: Env) {
  for (const key of SECRET_KEYS) {
    const value = env[key];
    if (typeof value === "string" && value) {
      process.env[key] = value;
    }
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    injectEnvToProcess(env);

    const url = new URL(request.url);
    console.log("[Worker] URL:", url.pathname);
    console.log("[Worker] GITHUB_TOKEN 可用:", !!process.env.GITHUB_TOKEN);

    // Image optimization via Cloudflare Images binding
    if (url.pathname === "/_vinext/image") {
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      });
    }

    // Delegate everything else to vinext
    return handler.fetch(request);
  },
};
